#FROM adoptopenjdk/openjdk11:jdk-11.0.2.9-slim
#WORKDIR /opt
#COPY target/*.jar /opt/app.jar
#ENTRYPOINT exec java $JAVA_OPTS -jar app.jar


# Use Java 17 base image
FROM eclipse-temurin:17-jdk-alpine

# Expose Eureka Server port
EXPOSE 8761

# Copy jar file
ADD target/*.jar app.jar

# Run application
ENTRYPOINT ["java", "-jar", "/app.jar"]