name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3